all:
  hosts:
    worker:
      ansible_host: nslrack27.nslab
      ansible_user: massimo
      vars:
        local_iface: cx5if0
        remote_iface: cx5if1
        local_addr: 192.168.127.0
        remote_addr: 192.168.127.0
        gpu_id: 0
